In [ ]:
import dspy.evaluate.metrics

In [3]:
from dspy.evaluate import answer_exact_match, answer_passage_match

import dspy

example = dspy.Example(answer="Eiffel Tower")
pred = dspy.Prediction(context=["The Eiffel Tower is in Paris.", "..."])


answer_passage_match(example, pred)  # True

True

In [9]:
testset = [
    dspy.Example(
        context="Password reset: click Forgot Password on login page.",
        question="I forgot my password, what should I do?",
        answer="Click Forgot Password on the login page."
    ).with_inputs("context", "question"),

    dspy.Example(
        context="Refunds are processed within 5 to 7 business days after approval.",
        question="When will I get my refund?",
        answer="Refunds are processed within 5 to 7 business days after approval."
    ).with_inputs("context", "question"),

    dspy.Example(
        context="Our mobile app is available on iOS and Android.",
        question="Do you have a desktop app?",
        answer="I don't know based on the provided information."
    ).with_inputs("context", "question"),
]

In [ ]:
from dspy.evaluate import SemanticF1

metric = SemanticF1()
model_ = "smollm2:360m-instruct-q4_K_M"
lm = dspy.LM(
    # model="groq/llama-3.1-8b-instant",
    model="groq/llama-3.1-8b-instant",
    # model=f"ollama_chat/{model_}",
    temperature=0.2,
    max_tokens=300,
)
dspy.configure(lm=lm)

In [28]:
model = dspy.Predict('question -> answer')
res = model(question="What is 2+2")

res

Prediction(
    answer='4'
)

In [1]:
from langchain_community.embeddings import Model2vecEmbeddings
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_postgres import PGVector

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# embeddings = Model2vecEmbeddings("minishlab/potion-base-8M")
connection = "postgresql+psycopg2://esai:1234@localhost:5432/postgres"

collection_name = "book_rag"

vector_store = PGVector(
    embeddings=embeddings,
    collection_name=collection_name,
    connection=connection,
    use_jsonb=True,
)

In [ ]:
# docs =

In [ ]:
# docs = [doc.page_content for doc in docs]
# docs

['worlds, although we will focus only on physical worlds in our discussion.\nRanganathan and Campbell (2003) see context as “any information about the\ncircumstances, objects or conditions surrounding a user that is considered\nrelevant to the interaction between the user and the ubiquitous computing\nenvironment”. Thus, context denotes additional information to what is tra-\nditionally represented in a user model, such as demographics or interests,\nand refers to “physical contexts (e.g., location, time), environmental contexts\n(weather, light and sound levels), informational contexts (stock quotes, sports\nscores), personal contexts (health, mood, schedule, activity), social contexts\n(group activity, social activity, whom one is in a room with), application con-\ntexts (emails, websites visited) and system contexts (network trafﬁc, status of\nprinters)” (Ranganathan and Campbell 2003). As becomes obvious from this\nenumeration, the border between user model and context is not well deﬁned.',
 'The system integrates different types of context awareness, such as location,\ntime, or weather, with recommendation functionality. Interestingly, one of the\nﬁndings of van Setten et al.(2004) is that a large share of users want to de-\ncide for themselves which contextual factors should be taken into account and',
 '12.2 Context-aware recommendation 291\n12.2 Context-aware recommendation\nContext awareness is a requirement for recommender systems that is partic-\nularly relevant in ubiquitous domains. Whereas some researchers denote vir-\ntually any domain aspect as context, we will denote as context only situation\nparameters that can be known by the system and may have an impact on the\nselection and ranking of recommendation results. Shilit et al. (1994) name the\nmost important aspects of context as where you are, who you are with, and\nwhat resources are nearby. Exploiting the current location of the user, his or\nher companions, and the availability of resources in his or her surroundings can\nconsiderably increase the perceived usefulness of a mobile application. Dix\net al. (2000) discuss awareness of space and location with respect to inter-\nactive mobile systems from a design perspective that also includes virtual\nworlds, although we will focus only on physical worlds in our discussion.',
 '13.2 Outlook 301\nfour different competitors. The accuracy improvements were reached by using\na combination of various techniques (T¨oscher et al. 2008). The main aspects\nwere the inclusion of the time aspect as a third aspect beside movies and users,\nthe calculation and combination of various predictors, new techniques such as\n“neighborhood-aware matrix factorization”, and the automatic ﬁne-tuning of\nparameters.\nContext awareness. Time aspects – as mentioned above – are only one of\nmany additional pieces of information that could be taken into account in\nrecommendation tasks. Recent works, for instance, have also tried to take\nadditional context aspects of the user into account. Under the termcontext,\nvarious aspects of the user’s situation can be subsumed:\nr A rather simple form of contextual information, which was discussed in\nChapter 12, is the user’s current geographical location, which might be\nexploited not only for ubiquitous or mobile recommendation scenarios but']

In [4]:
class RAG(dspy.Signature):
    context:list = dspy.InputField()
    user_query:str = dspy.InputField()
    answer = str = dspy.OutputField()

In [ ]:
# model = dspy.Predict(RAG)

In [5]:
class RAGPipeline(dspy.Module):
    def __init__(self, num_docs=5):
        self.num_docs = num_docs
        # self.respond = dspy.Predict("context, question -> response")
        self.respond = dspy.ChainOfThought("context, question -> response")

    def search(self,query):
        self.docs = vector_store.similarity_search(query=query)
        return self.docs

    def forward(self, question):
        context = self.search(question) # defined in tutorial linked below
        return self.respond(context=context, question=question)

In [9]:
import orjson
from dspy.utils import download

# Download question--answer pairs from the RAG-QA Arena "Tech" dataset.
download("https://huggingface.co/dspy/cache/resolve/main/ragqa_arena_tech_examples.jsonl")

with open("ragqa_arena_tech_examples.jsonl") as f:
    data = [orjson.loads(line) for line in f]

Downloading 'ragqa_arena_tech_examples.jsonl'...

In [14]:
# Inspect one datapoint.
data[0]
cot = dspy.ChainOfThought('question -> response')

In [11]:
data = [dspy.Example(**d).with_inputs('question') for d in data]

# Let's pick an `example` here from the data.
example = data[2]
example

Example({'question': 'why are my text messages coming up as maybe?', 'response': 'This is part of the Proactivity features new with iOS 9: It looks at info in emails to see if anyone with this number sent you an email and if it finds the phone number associated with a contact from your email, it will show you "Maybe". \n\nHowever, it has been suggested there is a bug in iOS 11.2 that can result in "Maybe" being displayed even when "Find Contacts in Other Apps" is disabled.', 'gold_doc_ids': [3956, 3957, 8034]}) (input_keys={'question'})

In [23]:
import random

random.Random(0).shuffle(data)
trainset, devset, testset = data[:2], data[2:5], data[5:10]

len(trainset), len(devset), len(testset)

(2, 3, 5)

In [15]:
from dspy.evaluate import SemanticF1

# Instantiate the metric.
metric = SemanticF1(decompositional=True)

# Produce a prediction from our `cot` module, using the `example` above as input.
pred = cot(**example.inputs())

# Compute the metric score for the prediction.
score = metric(example, pred)

print(f"Question: \t {example.question}\n")
print(f"Gold Response: \t {example.response}\n")
print(f"Predicted Response: \t {pred.response}\n")
print(f"Semantic F1 Score: {score:.2f}")

Question: 	 why are my text messages coming up as maybe?

Gold Response: 	 This is part of the Proactivity features new with iOS 9: It looks at info in emails to see if anyone with this number sent you an email and if it finds the phone number associated with a contact from your email, it will show you "Maybe".

However, it has been suggested there is a bug in iOS 11.2 that can result in "Maybe" being displayed even when "Find Contacts in Other Apps" is disabled.

Predicted Response: 	 To resolve the issue, try the following steps:
- Check the recipient's phone status to ensure it's not in airplane mode or do not disturb mode.
- Ask the recipient to check their phone storage space and delete any unnecessary files.
- Try sending the message again to see if it goes through.
- If the issue persists, check with your cellular provider to see if there are any outages or issues with the network.
- Consider using a different messaging app or service to see if the issue is specific to your current app.

Semantic F1 Score: 0.29

In [16]:
dspy.inspect_history(n=1)

[2026-02-24T12:32:34.172583]

System message:

Your input fields are:
1. `question` (str):
2. `ground_truth` (str):
3. `system_response` (str):
Your output fields are:
1. `reasoning` (str):
2. `ground_truth_key_ideas` (str): enumeration of key ideas in the ground truth
3. `system_response_key_ideas` (str): enumeration of key ideas in the system response
4. `discussion` (str): discussion of the overlap between ground truth and system response
5. `recall` (float): fraction (out of 1.0) of ground truth covered by the system response
6. `precision` (float): fraction (out of 1.0) of system response covered by the ground truth
All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## question ## ]]
{question}

[[ ## ground_truth ## ]]
{ground_truth}

[[ ## system_response ## ]]
{system_response}

[[ ## reasoning ## ]]
{reasoning}

[[ ## ground_truth_key_ideas ## ]]
{ground_truth_key_ideas}

[[ ## system_response_key_ideas ## ]]
{system_response_key_ideas}

[[ ## discussion ## ]]
{discussion}

[[ ## recall ## ]]
{recall}        # note: the value you produce must be a single float value

[[ ## precision ## ]]
{precision}        # note: the value you produce must be a single float value

[[ ## completed ## ]]
In adhering to this structure, your objective is:
        Compare a system's response to the ground truth to compute recall and precision of key ideas.
        You will first enumerate key ideas in each response, discuss their overlap, and then report recall and precision.


User message:

[[ ## question ## ]]
why are my text messages coming up as maybe?

[[ ## ground_truth ## ]]
This is part of the Proactivity features new with iOS 9: It looks at info in emails to see if anyone with this number sent you an email and if it finds the phone number associated with a contact from your email, it will show you "Maybe".

However, it has been suggested there is a bug in iOS 11.2 that can result in "Maybe" being displayed even when "Find Contacts in Other Apps" is disabled.

[[ ## system_response ## ]]
To resolve the issue, try the following steps:
- Check the recipient's phone status to ensure it's not in airplane mode or do not disturb mode.
- Ask the recipient to check their phone storage space and delete any unnecessary files.
- Try sending the message again to see if it goes through.
- If the issue persists, check with your cellular provider to see if there are any outages or issues with the network.
- Consider using a different messaging app or service to see if the issue is specific to your current app.

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## ground_truth_key_ideas ## ]]`, then `[[ ## system_response_key_ideas ## ]]`, then `[[ ## discussion ## ]]`, then `[[ ## recall ## ]]` (must be formatted as a valid Python float), then `[[ ## precision ## ]]` (must be formatted as a valid Python float), and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
The system response attempts to provide troubleshooting steps to resolve the issue of text messages being marked as "Maybe" in iOS. However, the ground truth explains that this is a feature of Proactivity in iOS 9, and a potential bug in iOS 11.2 may cause the issue even when "Find Contacts in Other Apps" is disabled.

[[ ## ground_truth_key_ideas ## ]]
1. Proactivity features in iOS 9
2. "Maybe" status in text messages
3. Bug in iOS 11.2
4. "Find Contacts in Other Apps" feature

[[ ## system_response_key_ideas ## ]]
1. Check recipient's phone status
2. Check recipient's phone storage space
3. Try sending the message again
4. Check with cellular provider for outages
5. Consider using a different messaging app

[[ ## discussion ## ]]
The system response and ground truth overlap in that both discuss the issue of text messages being marked as "Maybe". However, the system response provides troubleshooting steps that are not relevant to the actual cause of the issue, as explained in the ground truth. The system response does not address the potential bug in iOS 11.2.

[[ ## recall ## ]]
0.5

[[ ## precision ## ]]
0.2

[[ ## completed ## ]]

In [24]:
# Define an evaluator that we can re-use.
evaluate = dspy.Evaluate(devset=devset, metric=metric, num_threads=8,
                         display_progress=True, display_table=2)

# Evaluate the Chain-of-Thought program.
evaluate(cot)

Average Metric: 0.78 / 3 (25.9%): 100%|██████████| 3/3 [00:02<00:00,  1.49it/s]

2026/02/24 12:41:56 INFO dspy.evaluate.evaluate: Average Metric: 0.7773049645390071 / 3 (25.9%)

,question,example_response,gold_doc_ids,reasoning,pred_response,SemanticF1
0,i am missing the option to see the remaining battery life as time ...,One opinion advises that Apple deliberately removed the option to ...,"[6614, 6652, 6699, 6711, 6766, 6818]",This issue can be resolved by installing a third-party application...,"To install the Battery Indicator application, follow these steps: ...",✔️ [0.267]
1,why qt is not popular?,One reason why Qt may not be as popular is that it doesn't always ...,"[6882, 6883, 6884, 6886, 6890, 905, 5979, 5980, 6456, 1497]",The popularity of a programming language can be influenced by vari...,Qt's popularity can be attributed to its strengths in building com...,✔️ [0.511]

EvaluationResult(score=25.91, results=<list of 3 results>)

In [ ]:
# download("https://huggingface.co/dspy/cache/resolve/main/ragqa_arena_tech_corpus.jsonl")

Downloading 'ragqa_arena_tech_corpus.jsonl'...
  0%|          | 0/30 [10:02<?, ?it/s]

In [26]:
from model2vec import StaticModel

model = StaticModel.from_pretrained("minishlab/potion-base-8M")



max_characters = 1000  # for truncating >99th percentile of documents
topk_docs_to_retrieve = 5  # number of documents to retrieve per search query

with open("ragqa_arena_tech_corpus.jsonl") as f:
    corpus = [orjson.loads(line)['text'][:max_characters] for line in f]
    print(f"Loaded {len(corpus)} documents. Will encode them below.")

# embeddings = Model2vecEmbeddings("minishlab/potion-base-8M")
embedder = dspy.Embedder(model.encode)
search = dspy.retrievers.Embeddings(embedder=embedder, corpus=corpus, k=topk_docs_to_retrieve)

Loaded 28436 documents. Will encode them below.
Training a 32-byte FAISS index with 337 partitions, based on 28436 x 256-dim embeddings

In [27]:
class RAG(dspy.Module):
    def __init__(self):
        self.respond = dspy.ChainOfThought('context, question -> response')

    def forward(self, question):
        context = search(question).passages
        return self.respond(context=context, question=question)

In [28]:
rag = RAG()
rag(question="what are high memory and low memory on linux?")

Prediction(
    reasoning='Based on the provided context, high memory and low memory on Linux refer to different segments of memory that are used for different purposes. High memory is the segment of memory that user-space programs can address, while low memory is the segment of memory that the Linux kernel can address directly. The kernel must map high memory into its own address space if it needs to access it. This is relevant to the Linux kernel, and the tradeoff is that user-space applications cannot access kernel-space memory.',
    response='High memory on Linux refers to the segment of memory that user-space programs can address, while low memory is the segment of memory that the Linux kernel can address directly. The kernel must map high memory into its own address space if it needs to access it.'
)

In [29]:
dspy.inspect_history()

[2026-02-24T12:50:29.572537]

System message:

Your input fields are:
1. `context` (str):
2. `question` (str):
Your output fields are:
1. `reasoning` (str):
2. `response` (str):
All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## context ## ]]
{context}

[[ ## question ## ]]
{question}

[[ ## reasoning ## ]]
{reasoning}

[[ ## response ## ]]
{response}

[[ ## completed ## ]]
In adhering to this structure, your objective is:
        Given the fields `context`, `question`, produce the fields `response`.


User message:

[[ ## context ## ]]
[1] «The first reference to turn to is Linux Device Drivers (available both online and in book form), particularly chapter 15 which has a section on the topic. In an ideal world, every system component would be able to map all the memory it ever needs to access. And this is the case for processes on Linux and most operating systems: a 32-bit process can only access a little less than 2^32 bytes of virtual memory (in fact about 3GB on a typical Linux 32-bit architecture). It gets difficult for the kernel, which needs to be able to map the full memory of the process whose system call its executing, plus the whole physical memory, plus any other memory-mapped hardware device. So when a 32-bit kernel needs to map more than 4GB of memory, it must be compiled with high memory support. High memory is memory which is not permanently mapped in the kernels address space. (Low memory is the opposite: it is always mapped, so you can access it in the kernel simply by dereferencing a pointer.) When you a»
[2] «As far as I remember, High Memory is used for application space and Low Memory for the kernel. Advantage is that (user-space) applications cant access kernel-space memory.»
[3] «This is relevant to the Linux kernel; Im not sure how any Unix kernel handles this. The High Memory is the segment of memory that user-space programs can address. It cannot touch Low Memory. Low Memory is the segment of memory that the Linux kernel can address directly. If the kernel must access High Memory, it has to map it into its own address space first. There was a patch introduced recently that lets you control where the segment is. The tradeoff is that you can take addressable memory away from user space so that the kernel can have more memory that it does not have to map before using. Additional resources: http://tldp.org/HOWTO/KernelAnalysis-HOWTO-7.html http://linux-mm.org/HighMemory»
[4] «This is an old post, however, I would still take the liberty of putting up my thoughts here. Starting from down under, Linux would first divide the memory into pages (usually 4K per page on x86_64 system). Thereafter, virtual memory is created, whose mapping is done with physical memory using MMU (Memory Management Unit). Processes are allocated memory from the virtual memory area, so please note, when you see /proc/meminfo, you will see VMalloc* as the virtual memory details. Lets say you have a process which requests for memory (say 300MB - a web browser). The process would be allocated 300MB from the virtual memory, however, it is not necessary it is memory mapped (that is mapped to physical memory). There is concept of Copy on Write for memory management, whereby, if your processes actually uses the memory allocated from virtual memory (that is it does some write on the memory), only then it is mapped to physical memory. This assists the kernel to work properly in a multi-process e»
[5] «I dont know what other disadvantages there might be to compiling code as a loadable kernel module rather than directly into the kernel image, but to use your particular example, suppose that memory management was built as a kernel module rather than built into the kernel binary image itself. How would the kernel allocate the memory for an initial RAM disk? How would the kernel allocate the memory for the structures necessary to mount a file system? How would the kernel allocate the memory in which to load the memory management module? How would the memory management module know what memory has already been claimed by other parts of the kernel (possibly other loadable kernel modules which were needed to access the memory management module)? As you can see, this immediately opens a whole potential can of worms. Task scheduling is another similarly core kernel concept. From another perspective, what useful work could the kernel do without the memory management module? Its not like a hardw»

[[ ## question ## ]]
what are high memory and low memory on linux?

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## response ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
Based on the provided context, high memory and low memory on Linux refer to different segments of memory that are used for different purposes. High memory is the segment of memory that user-space programs can address, while low memory is the segment of memory that the Linux kernel can address directly. The kernel must map high memory into its own address space if it needs to access it. This is relevant to the Linux kernel, and the tradeoff is that user-space applications cannot access kernel-space memory.

[[ ## response ## ]]
High memory on Linux refers to the segment of memory that user-space programs can address, while low memory is the segment of memory that the Linux kernel can address directly. The kernel must map high memory into its own address space if it needs to access it.

[[ ## completed ## ]]

In [40]:
evaluate(RAG())

Average Metric: 1.13 / 3 (37.5%): 100%|██████████| 3/3 [00:00<00:00,  8.01it/s]

2026/02/24 13:00:49 INFO dspy.evaluate.evaluate: Average Metric: 1.1263974935246066 / 3 (37.5%)

,question,example_response,gold_doc_ids,reasoning,pred_response,SemanticF1
0,i am missing the option to see the remaining battery life as time ...,One opinion advises that Apple deliberately removed the option to ...,"[6614, 6652, 6699, 6711, 6766, 6818]","Based on the context provided, it seems that the option to show re...","You can consider using the ""Battery Time Remaining"" app by Han Lin...",✔️ [0.286]
1,why qt is not popular?,One reason why Qt may not be as popular is that it doesn't always ...,"[6882, 6883, 6884, 6886, 6890, 905, 5979, 5980, 6456, 1497]",The context provided suggests that the discussion revolves around ...,The lack of popularity of Qt might be due to its limitations or th...,✔️ [0.460]

EvaluationResult(score=37.55, results=<list of 3 results>)

In [41]:
tp = dspy.MIPROv2(metric=metric, auto="light", num_threads=2)  # use fewer threads if your rate limit is small

optimized_rag = tp.compile(RAG(), trainset=trainset,
                           max_bootstrapped_demos=2, max_labeled_demos=2)

2026/02/24 13:02:46 INFO dspy.teleprompt.mipro_optimizer_v2:
RUNNING WITH THE FOLLOWING LIGHT AUTO RUN SETTINGS:
num_trials: 10
minibatch: False
num_fewshot_candidates: 6
num_instruct_candidates: 3
valset size: 1

2026/02/24 13:02:46 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 1: BOOTSTRAP FEWSHOT EXAMPLES <==
2026/02/24 13:02:46 INFO dspy.teleprompt.mipro_optimizer_v2: These will be used as few-shot example candidates for our program and for creating instructions.

2026/02/24 13:02:46 INFO dspy.teleprompt.mipro_optimizer_v2: Bootstrapping N=6 sets of demonstrations...

Bootstrapping set 1/6
Bootstrapping set 2/6
Bootstrapping set 3/6

100%|██████████| 1/1 [00:00<00:00,  2.54it/s]

Bootstrapped 0 full traces after 0 examples for up to 1 rounds, amounting to 1 attempts.
Bootstrapping set 4/6

100%|██████████| 1/1 [00:00<00:00,  2.74it/s]

Bootstrapped 0 full traces after 0 examples for up to 1 rounds, amounting to 1 attempts.
Bootstrapping set 5/6

100%|██████████| 1/1 [00:00<00:00,  2.55it/s]

Bootstrapped 0 full traces after 0 examples for up to 1 rounds, amounting to 1 attempts.
Bootstrapping set 6/6

100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
2026/02/24 13:02:47 INFO dspy.teleprompt.mipro_optimizer_v2:
==> STEP 2: PROPOSE INSTRUCTION CANDIDATES <==
2026/02/24 13:02:47 INFO dspy.teleprompt.mipro_optimizer_v2: We will use the few-shot examples from the previous step, a generated dataset summary, a summary of the program code, and a randomly selected prompting tip to propose instructions.
2026/02/24 13:02:47 INFO dspy.teleprompt.mipro_optimizer_v2:
Proposing N=3 instructions...

Bootstrapped 0 full traces after 0 examples for up to 1 rounds, amounting to 1 attempts.

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: Proposed Instructions for Predictor 0:

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: 0: Given the fields `context`, `question`, produce the fields `response`.

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: 1: You are a technical support specialist, and you need to generate a response to a user's question based on a provided context. Your task is to produce a reasoning and response that addresses the user's query. Please describe the steps you would take to answer the question, using the context provided to inform your response.

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: 2: Given the context, question, and existing RAG model architecture, produce the fields `reasoning` and `response` using a Chain Of Thought (CoT) reasoner and conditioning on the retrieved context.

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2:

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: ==> STEP 3: FINDING OPTIMAL PROMPT PARAMETERS <==
2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: We will evaluate the program over a series of trials with different combinations of instructions and few-shot examples to find the optimal combination using Bayesian Optimization.

2026/02/24 13:02:48 INFO dspy.teleprompt.mipro_optimizer_v2: == Trial 1 / 10 - Full Evaluation of Default Program ==

Average Metric: 0.33 / 1 (33.3%): 100%|██████████| 1/1 [00:01<00:00,  1.33s/it]

2026/02/24 13:02:50 INFO dspy.evaluate.evaluate: Average Metric: 0.3333333333333333 / 1 (33.3%)
2026/02/24 13:02:50 INFO dspy.teleprompt.mipro_optimizer_v2: Default program score: 33.33

/home/esai/Desktop/python/dev/lib/python3.10/site-packages/optuna/_experimental.py:33: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  optuna_warn(
2026/02/24 13:02:50 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 2 / 10 =====

Average Metric: 0.63 / 1 (63.5%): 100%|██████████| 1/1 [00:01<00:00,  1.53s/it]

2026/02/24 13:02:51 INFO dspy.evaluate.evaluate: Average Metric: 0.6349086412071245 / 1 (63.5%)
2026/02/24 13:02:51 INFO dspy.teleprompt.mipro_optimizer_v2: Best full score so far! Score: 63.49
2026/02/24 13:02:51 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 63.49 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3'].
2026/02/24 13:02:51 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49]
2026/02/24 13:02:51 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:02:51 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:02:51 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 3 / 10 =====

Average Metric: 0.00 / 1 (0.0%): 100%|██████████| 1/1 [00:07<00:00,  7.39s/it]

2026/02/24 13:02:59 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 1 (0.0%)
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0'].
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0]
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 4 / 10 =====

Average Metric: 0.63 / 1 (63.5%): 100%|██████████| 1/1 [00:00<00:00,  6.12it/s]

2026/02/24 13:02:59 INFO dspy.evaluate.evaluate: Average Metric: 0.6349086412071245 / 1 (63.5%)
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 63.49 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 5'].
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49]
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:02:59 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 5 / 10 =====

  0%|          | 0/1 [00:00<?, ?it/s]

2026/02/24 13:03:06 ERROR dspy.utils.parallelizer: Error for Example({'question': 'how can i delete all lines in a file using vi?', 'response': 'Navigate to the first line using "1G" and then delete all lines up to the last one with "dG".  \nAlternatively, in the vi editor, you can use ":1,$d" to delete from the first to the last line.  \nIf preferred, the shorthand ":%d" can be employed in vi, which means to delete all lines.  \nAnother method is to issue "gg" to go to the top of the file before performing "dG" to delete every line until the file\'s end.  \nA similar approach that selects everything in the file is to use "ggVG" and then press "d" or "x" to delete everything.  \nFor a simple route, "ggdG" is a five-key command in vi that accomplishes the same result.  \nOne could also utilize " :!:>%" in vi to execute a shell command to truncate the current file.  \nA non-vi command to achieve file truncation is "truncate -s 0 file".  \nLastly, typing "and %d" within vi also clears the file\'s content.', 'gold_doc_ids': [2201, 2202, 2203, 2206, 2226, 2246, 2287, 5898, 5652]}) (input_keys={'question'}): litellm.RateLimitError: RateLimitError: GroqException - {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kgks8g58ewcad2jre1k9yrms` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5273, Requested 1143. Please try again in 4.16s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}
. Set `provide_traceback=True` for traceback.

Average Metric: 0.00 / 0 (0%): 100%|██████████| 1/1 [00:07<00:00,  7.08s/it]

2026/02/24 13:03:06 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 1 (0.0%)
2026/02/24 13:03:06 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 2'].
2026/02/24 13:03:06 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0]
2026/02/24 13:03:06 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:06 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:03:06 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 6 / 10 =====

Average Metric: 0.59 / 1 (58.5%): 100%|██████████| 1/1 [00:12<00:00, 12.33s/it]

2026/02/24 13:03:18 INFO dspy.evaluate.evaluate: Average Metric: 0.5853658536585366 / 1 (58.5%)
2026/02/24 13:03:18 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 58.54 with parameters ['Predictor 0: Instruction 0', 'Predictor 0: Few-Shot Set 5'].
2026/02/24 13:03:18 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0, 58.54]
2026/02/24 13:03:18 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:18 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:03:18 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 7 / 10 =====

Average Metric: 0.00 / 1 (0.0%): 100%|██████████| 1/1 [00:03<00:00,  3.70s/it]

2026/02/24 13:03:22 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 1 (0.0%)
2026/02/24 13:03:22 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 0'].
2026/02/24 13:03:22 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0, 58.54, 0.0]
2026/02/24 13:03:22 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:22 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:03:22 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 8 / 10 =====

  0%|          | 0/1 [00:00<?, ?it/s]

2026/02/24 13:03:29 ERROR dspy.utils.parallelizer: Error for Example({'question': 'how can i delete all lines in a file using vi?', 'response': 'Navigate to the first line using "1G" and then delete all lines up to the last one with "dG".  \nAlternatively, in the vi editor, you can use ":1,$d" to delete from the first to the last line.  \nIf preferred, the shorthand ":%d" can be employed in vi, which means to delete all lines.  \nAnother method is to issue "gg" to go to the top of the file before performing "dG" to delete every line until the file\'s end.  \nA similar approach that selects everything in the file is to use "ggVG" and then press "d" or "x" to delete everything.  \nFor a simple route, "ggdG" is a five-key command in vi that accomplishes the same result.  \nOne could also utilize " :!:>%" in vi to execute a shell command to truncate the current file.  \nA non-vi command to achieve file truncation is "truncate -s 0 file".  \nLastly, typing "and %d" within vi also clears the file\'s content.', 'gold_doc_ids': [2201, 2202, 2203, 2206, 2226, 2246, 2287, 5898, 5652]}) (input_keys={'question'}): litellm.RateLimitError: RateLimitError: GroqException - {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kgks8g58ewcad2jre1k9yrms` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 4945, Requested 1143. Please try again in 880ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}
. Set `provide_traceback=True` for traceback.

Average Metric: 0.00 / 0 (0%): 100%|██████████| 1/1 [00:06<00:00,  6.74s/it]

2026/02/24 13:03:29 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 1 (0.0%)
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5'].
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0, 58.54, 0.0, 0.0]
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 9 / 10 =====

Average Metric: 0.63 / 1 (63.5%): 100%|██████████| 1/1 [00:00<00:00,  6.09it/s]

2026/02/24 13:03:29 INFO dspy.evaluate.evaluate: Average Metric: 0.6349086412071245 / 1 (63.5%)
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 63.49 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 4'].
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0, 58.54, 0.0, 0.0, 63.49]
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: ========================


2026/02/24 13:03:29 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 10 / 10 =====

  0%|          | 0/1 [00:00<?, ?it/s]

2026/02/24 13:03:38 ERROR dspy.utils.parallelizer: Error for Example({'question': 'how can i delete all lines in a file using vi?', 'response': 'Navigate to the first line using "1G" and then delete all lines up to the last one with "dG".  \nAlternatively, in the vi editor, you can use ":1,$d" to delete from the first to the last line.  \nIf preferred, the shorthand ":%d" can be employed in vi, which means to delete all lines.  \nAnother method is to issue "gg" to go to the top of the file before performing "dG" to delete every line until the file\'s end.  \nA similar approach that selects everything in the file is to use "ggVG" and then press "d" or "x" to delete everything.  \nFor a simple route, "ggdG" is a five-key command in vi that accomplishes the same result.  \nOne could also utilize " :!:>%" in vi to execute a shell command to truncate the current file.  \nA non-vi command to achieve file truncation is "truncate -s 0 file".  \nLastly, typing "and %d" within vi also clears the file\'s content.', 'gold_doc_ids': [2201, 2202, 2203, 2206, 2226, 2246, 2287, 5898, 5652]}) (input_keys={'question'}): litellm.RateLimitError: RateLimitError: GroqException - {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kgks8g58ewcad2jre1k9yrms` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5259, Requested 750. Please try again in 90ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}
. Set `provide_traceback=True` for traceback.

Average Metric: 0.00 / 0 (0%): 100%|██████████| 1/1 [00:09<00:00,  9.43s/it]

2026/02/24 13:03:38 INFO dspy.evaluate.evaluate: Average Metric: 0.0 / 1 (0.0%)
2026/02/24 13:03:38 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 0.0 with parameters ['Predictor 0: Instruction 2', 'Predictor 0: Few-Shot Set 5'].
2026/02/24 13:03:38 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0, 58.54, 0.0, 0.0, 63.49, 0.0]
2026/02/24 13:03:38 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:38 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2026/02/24 13:03:38 INFO dspy.teleprompt.mipro_optimizer_v2: ===== Trial 11 / 10 =====

Average Metric: 0.63 / 1 (63.5%): 100%|██████████| 1/1 [00:00<00:00,  5.30it/s]

2026/02/24 13:03:39 INFO dspy.evaluate.evaluate: Average Metric: 0.6349086412071245 / 1 (63.5%)
2026/02/24 13:03:39 INFO dspy.teleprompt.mipro_optimizer_v2: Score: 63.49 with parameters ['Predictor 0: Instruction 1', 'Predictor 0: Few-Shot Set 3'].
2026/02/24 13:03:39 INFO dspy.teleprompt.mipro_optimizer_v2: Scores so far: [33.33, 63.49, 0.0, 63.49, 0.0, 58.54, 0.0, 0.0, 63.49, 0.0, 63.49]
2026/02/24 13:03:39 INFO dspy.teleprompt.mipro_optimizer_v2: Best score so far: 63.49
2026/02/24 13:03:39 INFO dspy.teleprompt.mipro_optimizer_v2: =========================


2026/02/24 13:03:39 INFO dspy.teleprompt.mipro_optimizer_v2: Returning best identified program with score 63.49!

In [42]:
baseline = rag(question="cmd+tab does not work on hidden or minimized windows")
print(baseline.response)

To restore a hidden or minimized window using `cmd+tab`, follow these steps:

1. Use `cmd+tab` to switch to the application icon.
2. Hold `cmd` and use the down arrow key to enter App Exposé.
3. Navigate to the minimized window using the arrow keys.
4. Press `return` to restore the window.

Alternatively, you can use `ctrl+down arrow` to directly enter App Exposé and select the minimized window.

In [43]:
pred = optimized_rag(question="cmd+tab does not work on hidden or minimized windows")
print(pred.response)

According to the context, there are a few alternative methods to restore or switch between minimized windows using the keyboard. You can try the following:

- Use Command + Tab to switch to the application with minimized windows, but don't release the Command key. While still holding Command down, tap the Down arrow key to enter App Exposé. Once in App Exposé, you can use the arrow keys to select the minimized window you want to restore.
- Alternatively, you can use Control + Down arrow to enter App Exposé, then use the arrow keys to select the minimized window you want to restore.
- If you want to restore all minimized windows of an application, you can use Option + Return after selecting the application in App Exposé.

These methods should allow you to switch between minimized windows using the keyboard.

In [54]:
rag.inspect_history()

[2026-02-24T13:04:08.962346]

System message:

Your input fields are:
1. `context` (str):
2. `question` (str):
Your output fields are:
1. `reasoning` (str):
2. `response` (str):
All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## context ## ]]
{context}

[[ ## question ## ]]
{question}

[[ ## reasoning ## ]]
{reasoning}

[[ ## response ## ]]
{response}

[[ ## completed ## ]]
In adhering to this structure, your objective is:
        Given the fields `context`, `question`, produce the fields `response`.


User message:

[[ ## context ## ]]
[1] «Shift-CMD-F is for presentation mode and will hide the tabs. You want full screen mode instead, so use Control-CMD-F. Tabs will show in full screen mode.»
[2] «To restore one of many minimized windows using only the keyboard, you have two choices: While using Cmd + tab (eg. changing applications): Start with a minimized window Cmd + tab to the application icon (Continue to hold Cmd) While holding Cmd, push the ↑ (or ↓) arrow key on the keyboard. This will bring up a list of all the applications windows (You can release key command key once the window list view comes up if you like) Push the down arrow key (↓) to select the minimized windows. Use the left and right arrow keys (← or →) to select the minimized window you want Push Return or Enter to restore the window and bring it into focus (make it the selected window) (Tested on OS X Mountain Lion) Or, Directly when the application is already the current application: Steps as above, but instead of steps 2 and 3 (Cmd + tab and arrow keys): Start with a minimized window Control + ↓. If App Exposé is selected in Trackpad preferences, you can also swipe down with three fingers. OS X Mountain Lion»
[3] «UK Keyboard [see below for other languages] Cmd ⌘ ` Cmd ⌘ Shift ⇧ ` to go the other way. Left of z on a UK keyboard [non-shifted ~ ] Note: This only works if all windows are in the same Space, not if they are spread over multiple Spaces, which includes fullscreen. To overcome this, use Cmd ⌘Tab as usual and on the icon of the application you want to switch windows in press the down arrow key (with Cmd ⌘ still pressed). Then use left/right keys to navigate to the desired window across spaces and desktops. You can also achieve this by clicking the apps icon in the Dock - this method will also switch to fullscreen windows, which the other methods will not.. From comments - You can check which key command it is for your language by switching to Finder, then look at the Window menu for Cycle through windows... BTW, specifically in Chrome, Safari & Firefox, but no other app I know of on Mac, Cmd ⌘ (number) will select individual tabs on the frontmost window. It also would appear that Cmd ⌘ `»
[4] «A very quick keyboard method to un-minimize a specific window or un-minimize all of an apps minimized windows is this: Command ⌘+Tab ⇥ to the app with minimized windows, but dont release the Command ⌘ key. While still holding Command ⌘ down, tap Down ↓ or 1 (easy 1-handed access) to enter App Exposé. Once in App Exposé, all keys can be released. To un-minimize all windows, select any window with arrow keys, then press Option ⌥+Return ↩. To un-minimize a specific window, navigate to the window you want with the arrow keys, then press Return ↩.»
[5] «Im from the same boat; the best native keyboard-only Ive found is CTRL-DOWN-Arrow; (you enter app expose) DOWN-arrow; (if there are any minimized windows, thisll put a cursor on one) LEFT-arrow/RIGHT-arrow (to select from multiple minimized windows) or hold OPT if you want all of them restored. RETURN alternative step1: getting into app expose before youve alt-cmded to an app: with CMD still held down, (the task switcher is visible) tap DOWN, or UP, or 1 (now in app expose) The above shows only one apps minimized windows at a time; for selecting from any minimized window regardless of app, CTRL-F3 moves focus to the dock, and you can arrow left to get to the minimized list. if your CTRL-F3 instead shows you the app-expose, try FN-CTRL-F3. (In my settings/keyboard, Ive flagged Use all F1, F2, etc. keys as standard function keys) Some apps have specific alternatives; I use Terminals CMD-window_number, which unminimizes and focuses that window.»

[[ ## question ## ]]
cmd+tab does not work on hidden or minimized windows

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## response ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
The provided context explains various keyboard shortcuts for navigating and managing windows on a Mac. However, the question specifically asks about using `cmd+tab` on hidden or minimized windows. According to the context, `cmd+tab` does not work directly on hidden or minimized windows. Instead, you need to use `cmd+tab` to switch to the application icon, then hold `cmd` and use the down arrow key to enter App Exposé, where you can navigate to the minimized window and restore it.

[[ ## response ## ]]
To restore a hidden or minimized window using `cmd+tab`, follow these steps:

1. Use `cmd+tab` to switch to the application icon.
2. Hold `cmd` and use the down arrow key to enter App Exposé.
3. Navigate to the minimized window using the arrow keys.
4. Press `return` to restore the window.

Alternatively, you can use `ctrl+down arrow` to directly enter App Exposé and select the minimized window.

[[ ## completed ## ]]

In [53]:
optimized_rag.inspect_history()

[2026-02-24T13:04:12.504740]

System message:

Your input fields are:
1. `context` (str):
2. `question` (str):
Your output fields are:
1. `reasoning` (str):
2. `response` (str):
All interactions will be structured in the following way, with the appropriate values filled in.

[[ ## context ## ]]
{context}

[[ ## question ## ]]
{question}

[[ ## reasoning ## ]]
{reasoning}

[[ ## response ## ]]
{response}

[[ ## completed ## ]]
In adhering to this structure, your objective is:
        You are a technical support specialist, and you need to generate a response to a user's question based on a provided context. Your task is to produce a reasoning and response that addresses the user's query. Please describe the steps you would take to answer the question, using the context provided to inform your response.


User message:

This is an example of the task, though some input or output fields are not supplied.

[[ ## question ## ]]
how to go to the previous working directory in terminal?


Assistant message:

[[ ## reasoning ## ]]
Not supplied for this particular example.

[[ ## response ## ]]
To navigate back to the previous working directory, you can use the command "$ cd"or "cd $OLDPWD".
For those seeking an alternative method without the directory echo, "cd ~-" is suggested as it performs the same function more succinctly.
For a more organized approach, particularly when planning to return to the starting directory, it's recommended to utilize "pushd" and "popd".

[[ ## completed ## ]]


User message:

[[ ## context ## ]]
[1] «Shift-CMD-F is for presentation mode and will hide the tabs. You want full screen mode instead, so use Control-CMD-F. Tabs will show in full screen mode.»
[2] «To restore one of many minimized windows using only the keyboard, you have two choices: While using Cmd + tab (eg. changing applications): Start with a minimized window Cmd + tab to the application icon (Continue to hold Cmd) While holding Cmd, push the ↑ (or ↓) arrow key on the keyboard. This will bring up a list of all the applications windows (You can release key command key once the window list view comes up if you like) Push the down arrow key (↓) to select the minimized windows. Use the left and right arrow keys (← or →) to select the minimized window you want Push Return or Enter to restore the window and bring it into focus (make it the selected window) (Tested on OS X Mountain Lion) Or, Directly when the application is already the current application: Steps as above, but instead of steps 2 and 3 (Cmd + tab and arrow keys): Start with a minimized window Control + ↓. If App Exposé is selected in Trackpad preferences, you can also swipe down with three fingers. OS X Mountain Lion»
[3] «UK Keyboard [see below for other languages] Cmd ⌘ ` Cmd ⌘ Shift ⇧ ` to go the other way. Left of z on a UK keyboard [non-shifted ~ ] Note: This only works if all windows are in the same Space, not if they are spread over multiple Spaces, which includes fullscreen. To overcome this, use Cmd ⌘Tab as usual and on the icon of the application you want to switch windows in press the down arrow key (with Cmd ⌘ still pressed). Then use left/right keys to navigate to the desired window across spaces and desktops. You can also achieve this by clicking the apps icon in the Dock - this method will also switch to fullscreen windows, which the other methods will not.. From comments - You can check which key command it is for your language by switching to Finder, then look at the Window menu for Cycle through windows... BTW, specifically in Chrome, Safari & Firefox, but no other app I know of on Mac, Cmd ⌘ (number) will select individual tabs on the frontmost window. It also would appear that Cmd ⌘ `»
[4] «A very quick keyboard method to un-minimize a specific window or un-minimize all of an apps minimized windows is this: Command ⌘+Tab ⇥ to the app with minimized windows, but dont release the Command ⌘ key. While still holding Command ⌘ down, tap Down ↓ or 1 (easy 1-handed access) to enter App Exposé. Once in App Exposé, all keys can be released. To un-minimize all windows, select any window with arrow keys, then press Option ⌥+Return ↩. To un-minimize a specific window, navigate to the window you want with the arrow keys, then press Return ↩.»
[5] «Im from the same boat; the best native keyboard-only Ive found is CTRL-DOWN-Arrow; (you enter app expose) DOWN-arrow; (if there are any minimized windows, thisll put a cursor on one) LEFT-arrow/RIGHT-arrow (to select from multiple minimized windows) or hold OPT if you want all of them restored. RETURN alternative step1: getting into app expose before youve alt-cmded to an app: with CMD still held down, (the task switcher is visible) tap DOWN, or UP, or 1 (now in app expose) The above shows only one apps minimized windows at a time; for selecting from any minimized window regardless of app, CTRL-F3 moves focus to the dock, and you can arrow left to get to the minimized list. if your CTRL-F3 instead shows you the app-expose, try FN-CTRL-F3. (In my settings/keyboard, Ive flagged Use all F1, F2, etc. keys as standard function keys) Some apps have specific alternatives; I use Terminals CMD-window_number, which unminimizes and focuses that window.»

[[ ## question ## ]]
cmd+tab does not work on hidden or minimized windows

Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## response ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.


Response:

[[ ## reasoning ## ]]
The user is experiencing an issue with using the Command + Tab shortcut to switch between windows, but it's not working for hidden or minimized windows. Based on the provided context, I'll look for alternative methods to restore or switch between minimized windows using the keyboard.

[[ ## response ## ]]
According to the context, there are a few alternative methods to restore or switch between minimized windows using the keyboard. You can try the following:

- Use Command + Tab to switch to the application with minimized windows, but don't release the Command key. While still holding Command down, tap the Down arrow key to enter App Exposé. Once in App Exposé, you can use the arrow keys to select the minimized window you want to restore.
- Alternatively, you can use Control + Down arrow to enter App Exposé, then use the arrow keys to select the minimized window you want to restore.
- If you want to restore all minimized windows of an application, you can use Option + Return after selecting the application in App Exposé.

These methods should allow you to switch between minimized windows using the keyboard.

[[ ## completed ## ]]

In [45]:
optimized_rag.save("optimized_rag.json")